In [38]:
import pandas as pd
import numpy as np

In [39]:
# data ingestion or reading the data
data=pd.read_csv(r'C:\DimondPricePrediction\notebooks\gemestone.csv')

In [40]:
#data.drop(labels=["id"],axis=1,inplace=True)

In [41]:
## information about data
data.head(10)

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z,price
0,1,0.30,Ideal,E,SI1,62.1,58.0,4.27,4.29,2.66,499
1,2,0.33,Premium,G,IF,60.8,58.0,4.42,4.46,2.70,984
2,3,0.90,Very Good,E,VVS2,62.2,60.0,6.04,6.12,3.78,6289
3,4,0.42,Ideal,F,VS1,61.6,56.0,4.82,4.80,2.96,1082
4,5,0.31,Ideal,F,VVS1,60.4,59.0,4.35,4.43,2.65,779
5,6,1.02,Ideal,D,VS2,61.5,56.0,6.46,6.49,3.99,9502
6,7,1.01,Good,H,SI1,63.7,60.0,6.35,6.30,4.03,4836
7,8,0.50,Premium,E,SI1,61.5,62.0,5.09,5.06,3.12,1415
8,9,1.21,Good,H,SI1,63.8,64.0,6.72,6.63,4.26,5407
9,10,0.35,Ideal,F,VS2,60.5,57.0,4.52,4.60,2.76,706

In [42]:
# removing null values from the data
data.isnull().sum()

Unnamed: 0      0
carat           0
cut             0
color           0
clarity         0
depth         697
table           0
x               0
y               0
z               0
price           0
dtype: int64

In [43]:
# find the mean of the depth value
import numpy as np
data_mean=data['depth'].mean()

In [44]:
# filling the null values 
data['depth'].fillna(data_mean,inplace=True)

In [45]:

data.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
x             0
y             0
z             0
price         0
dtype: int64

In [46]:

# collecting independent feature in the x 
X=data.drop(labels=["price"],axis=1)

In [47]:
# dependent features
y=data[["price"]]

In [48]:
# independent features
X

,Unnamed: 0,carat,cut,color,clarity,depth,table,x,y,z
0,1,0.30,Ideal,E,SI1,62.1,58.0,4.27,4.29,2.66
1,2,0.33,Premium,G,IF,60.8,58.0,4.42,4.46,2.70
2,3,0.90,Very Good,E,VVS2,62.2,60.0,6.04,6.12,3.78
3,4,0.42,Ideal,F,VS1,61.6,56.0,4.82,4.80,2.96
4,5,0.31,Ideal,F,VVS1,60.4,59.0,4.35,4.43,2.65
...,...,...,...,...,...,...,...,...,...,...
26962,26963,1.11,Premium,G,SI1,62.3,58.0,6.61,6.52,4.09
26963,26964,0.33,Ideal,H,IF,61.9,55.0,4.44,4.42,2.74
26964,26965,0.51,Premium,E,VS2,61.7,58.0,5.12,5.15,3.17
26965,26966,0.27,Very Good,F,VVS2,61.8,56.0,4.19,4.20,2.60
26966,26967,1.25,Premium,J,SI1,62.0,58.0,6.90,6.88,4.27

In [49]:
y

       price
0        499
1        984
2       6289
3       1082
4        779
...      ...
26962   5408
26963   1114
26964   1656
26965    682
26966   5166

[26967 rows x 1 columns]

In [50]:
categorical_cols=X.select_dtypes(include='object').columns

In [51]:
numerical_cols=X.select_dtypes(exclude='object').columns

In [52]:
numerical_cols

Index(['Unnamed: 0', 'carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [53]:
X.select_dtypes(include='object')

             cut color clarity
0          Ideal     E     SI1
1        Premium     G      IF
2      Very Good     E    VVS2
3          Ideal     F     VS1
4          Ideal     F    VVS1
...          ...   ...     ...
26962    Premium     G     SI1
26963      Ideal     H      IF
26964    Premium     E     VS2
26965  Very Good     F    VVS2
26966    Premium     J     SI1

[26967 rows x 3 columns]

In [54]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [55]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [56]:
# Piepline :
# pipeline is set of automated processes or tools that are connected in a sequence to
# perform a specific tasks

In [57]:
num_pipeline=Pipeline(
    
    
    steps=[
        
        ('imputer',SimpleImputer()), # it handle missing values
        ('scaler', StandardScaler())  # it reduce the size of the data
    ]
    
    
)

In [58]:
cat_pipeline=Pipeline(
    
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')), # handle the repeated values 
        ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories])) # provide the ranking for the data 
    ]
    
)

In [59]:
preprocessor=ColumnTransformer(
    [
        
        ('num_pipeline',num_pipeline,numerical_cols),
        ('cat_pipeline',cat_pipeline,categorical_cols)
    ]
)

In [60]:

## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=30)

In [61]:
preprocessor.fit_transform(X_train)

array([[-1.14466822,  0.56167397,  0.31998605, ...,  4.        ,
         3.        ,  4.        ],
       [-1.04652162, -0.60408689, -0.39665083, ...,  2.        ,
         1.        ,  2.        ],
       [ 1.20300362, -0.52081826, -0.25332345, ...,  4.        ,
         4.        ,  1.        ],
       ...,
       [ 0.22436753,  1.87315495,  0.74996818, ...,  2.        ,
         4.        ,  4.        ],
       [-1.15971822, -1.04124722,  1.03662293, ...,  1.        ,
         0.        ,  1.        ],
       [-0.97860366, -0.54163542, -0.68330558, ...,  4.        ,
         0.        ,  2.        ]])

In [62]:
preprocessor.transform(X_test)

array([[ 1.04096134e-01, -8.33075636e-01,  1.76658675e-01, ...,
         3.00000000e+00,  1.00000000e+00,  2.00000000e+00],
       [ 6.13995381e-01,  2.91050915e-01, -9.69960326e-01, ...,
         3.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.05253826e-01,  6.24125449e-01, -3.96650825e-01, ...,
         3.00000000e+00,  6.00000000e+00,  3.00000000e+00],
       ...,
       [ 5.02342367e-01, -1.04124722e+00,  8.21631863e-01, ...,
         2.00000000e+00,  2.00000000e+00,  3.00000000e+00],
       [-1.68209482e+00,  4.36771024e-01, -1.81659763e-01, ...,
         3.00000000e+00,  3.00000000e+00,  2.00000000e+00],
       [ 5.55210326e-01,  4.15953865e-01, -5.97870139e-03, ...,
         3.00000000e+00,  1.00000000e+00,  1.00000000e+00]])

In [63]:
# accessing the column name of the features over present in the data
preprocessor.get_feature_names_out()

array(['num_pipeline__Unnamed: 0', 'num_pipeline__carat',
       'num_pipeline__depth', 'num_pipeline__table', 'num_pipeline__x',
       'num_pipeline__y', 'num_pipeline__z', 'cat_pipeline__cut',
       'cat_pipeline__color', 'cat_pipeline__clarity'], dtype=object)

In [64]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [65]:
X_train

,num_pipeline__Unnamed: 0,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-1.144668,0.561674,0.319986,-0.651005,0.704838,0.692859,0.723432,4.0,3.0,4.0
1,-1.046522,-0.604087,-0.396651,1.589878,-0.533052,-0.486169,-0.533329,2.0,1.0,2.0
2,1.203004,-0.520818,-0.253323,-1.099182,-0.409263,-0.376688,-0.410385,4.0,4.0,1.0
3,-1.390742,-0.999613,0.248322,-1.099182,-1.178523,-1.134635,-1.107067,4.0,4.0,4.0
4,0.665320,0.228599,0.964959,-0.651005,0.413049,0.330729,0.477544,2.0,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...
18871,-1.676435,-0.187744,-2.044916,2.038055,0.103577,0.044393,-0.150837,3.0,3.0,2.0
18872,-0.187256,0.436771,0.319986,0.245348,0.607575,0.558113,0.614148,3.0,3.0,2.0
18873,0.224368,1.873155,0.749968,-0.202829,1.535992,1.543444,1.611360,2.0,4.0,4.0
18874,-1.159718,-1.041247,1.036623,-0.202829,-1.346523,-1.260959,-1.189030,1.0,0.0,1.0
18875,-0.978604,-0.541635,-0.683306,-0.202829,-0.426947,-0.359845,-0.451366,4.0,0.0,2.0

In [66]:
X_test

,num_pipeline__Unnamed: 0,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,0.104096,-0.833076,0.176659,1.589878,-0.904419,-0.898829,-0.861180,3.0,1.0,2.0
1,0.613995,0.291051,-0.969960,0.693525,0.536838,0.532848,0.409242,3.0,1.0,1.0
2,0.105254,0.624125,-0.396651,-0.202829,0.819784,0.734967,0.709771,3.0,6.0,3.0
3,0.325344,0.832297,-1.328279,2.934408,0.978942,0.886556,0.737092,1.0,1.0,2.0
4,-0.089496,-1.041247,-0.253323,0.693525,-1.293470,-1.210430,-1.243672,2.0,3.0,7.0
...,...,...,...,...,...,...,...,...,...,...
8086,-1.366173,-0.166927,-1.471606,0.693525,0.032840,0.069658,-0.109855,2.0,1.0,1.0
8087,0.109627,-0.166927,-0.969960,0.245348,0.032840,0.069658,-0.055213,2.0,3.0,5.0
8088,0.502342,-1.041247,0.821632,-0.202829,-1.293470,-1.218851,-1.161709,2.0,2.0,3.0
8089,-1.682095,0.436771,-0.181660,0.693525,0.660627,0.583378,0.586827,3.0,3.0,2.0
8090,0.555210,0.415954,-0.005979,1.141701,0.607575,0.600221,0.545846,3.0,1.0,1.0

In [67]:
"""linear regression
ridge regression
lasso regression
elastic net"""

'linear regression\nridge regression\nlasso regression\nelastic net'

In [68]:
## Model Training

# importing the machien learning model
#import the perfomance matrices

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [69]:
import numpy as np
# here i am evaluating my model
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [70]:
## Train multiple models
# for that i crate a list which have multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

In [71]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [72]:
list(models)

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [73]:
# using it we get the values of the models
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(model)

LinearRegression()
Lasso()
Ridge()
ElasticNet()

In [74]:
models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet'])

In [75]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet()])

In [76]:

# here i tarain my model which are linearRegression lasso ridge elastic net
for i in range(len(list(models))):
    # here i get each model 
    model=list(models.values())[i]
    # here i train my machine learning model on the train data
    
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    #this is a validation(test) score
    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 1179.6440186404982
MAE: 813.7641042991066
R2 score 91.44174691692477
===================================


Lasso
Model Training Performance
RMSE: 1180.8322050843321
MAE: 815.5181868913214
R2 score 91.42449777844838
===================================


Ridge
Model Training Performance
RMSE: 1179.8230019372295
MAE: 814.039057456133
R2 score 91.43914969177375
===================================


Elasticnet
Model Training Performance
RMSE: 1597.661748694811
MAE: 1070.688898402669
R2 score 84.30169147760799
===================================

In [77]:
trained_model_list

[]

In [78]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [79]:
r2_list

[0.9144174691692477,
 0.9142449777844839,
 0.9143914969177375,
 0.8430169147760799]